CREATE TABLE [dbo].[Order] (
	Uid UNIQUEIDENTIFIER NOT NULL,
	Title NVARCHAR(256) NULL,
	CreationDate DATETIME NOT NULL,
	ModifiedDate DATETIME NOT NULL,
	CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED ([Uid] ASC)
);